### ISSUE TITLE
Ephemeral znodes on close throw uncaught exception

### ISSUE THREAD

**Issue by datacoda** [twitter-archive/scala-zookeeper-client#5]
Hi,

For ephemeral znodes, it looks like ZooKeeper triggers the deletedData watch sometimes late.

<pre>
zookeeper.ClientCnxn     - Error while calling watcher
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /test/cluster:2124/service/sim/n-0000000001
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:90)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:42)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:809)
        at com.twitter.zookeeper.ZooKeeperClient.deletedData$1(ZooKeeperClient.scala:179)
        at com.twitter.zookeeper.ZooKeeperClient$$anon$2.process(ZooKeeperClient.scala:194)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:506)
</pre>

To reproduce, you can create an ephem znode and then call zk.close()  It doesn't occur always, but often enough.  I'm getting around it by adding a catch for KeeperException.ConnectionLossException where it's doing zk.exists (line 179: ZooKeeperClient.scala)  You might be able to get around it by calling zk.isAlive as well.

P.S. I'm not deleting the node before calling close.

**Comment by datacoda** [comment]
Closing due to deprecation.
